

# RAVDESS file format
url:          'https://zenodo.org/record/1188976/files/Audio_Speech_Actors_01-24.zip?download=1'
actors:       [ '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24']
emotions:     [ '01', '02', '03', '04', '05', '06', '07', '08']
intensities:  [ '01',  '02']
repetitions:  [ '01',  '02']
statements:   [ '01',  '02']

# audio parameters
sample_rate : 48000 # verified for all the files


# filepath parameters
raw_audio_data              : 'data/raw/'
speech1_data_raw            : 'data/interim/speech1_data.h5'
speech2_data_raw            : 'data/interim/speech2_data.h5'
speech1_data_refactor       : 'data/interim/speech1_refactor.h5'
speech2_data_refactor       : 'data/interim/speech2_refactor.h5'
speech1_no_intensity        : 'data/interim/speech1_no_intensity.h5'
speech2_no_intensity        : 'data/interim/speech2_no_intensity.h5'
speech1_MelSpec             : 'data/interim/speech1_MelSpec.h5'
speech2_MelSpec             : 'data/interim/speech2_MelSpec.h5'     

